# help_info:
#   intro: 'æ¶©å›¾åŠŸèƒ½å¯ä»¥è®©ä½ é€šè¿‡ä¸€äº›æŒ‡ä»¤æ¥æŸ¥çœ‹pç«™çš„æ¶©å›¾, å½“å‰æ•°æ®åº“ä¸­å·²ä¿å­˜è¶…è¿‡10ä¸‡æ¡ä¿¡æ¯'
#   func:
#     paid:
#       description: 'æ ¹æ®pç«™ä½œå“idè·å–å›¾ç‰‡å’Œä½œå“è¯¦æƒ…'
#       example: '/paid 123456'
#       paras: 
#         pç«™ä½œå“id: {required: true, prompt: "ä¸€èˆ¬ä¸º10ä½æ•°å­—"}
#     puid:
#       description:
#       example:
#       paras:

#   configs:
#     allowance:
#       description: 'å…è®¸ä»æ•°æ®åº“ä¸­å–å‡ºçš„å›¾ç‰‡ç±»å‹'
#       paras: 
#         ai: {prompt: "1ä¸ºå…è®¸aiå›¾ç‰‡, 0ä¸ºç¦æ­¢aiå›¾ç‰‡"}
#         r18: {prompt: "1ä¸ºå…è®¸r18å›¾ç‰‡, 0ä¸ºç¦æ­¢r18å›¾ç‰‡"}
#     cache_threshold:
#       description:
#       paras:
#     subscribe_puser_list:
#       description:
#       paras:


# å…è®¸ä»æ•°æ®åº“å–å‡ºçš„å›¾ç‰‡ç±»å‹
allowance:
  ai:
    default: false
    '670404622': true
  r18:
    default: false
    '670404622': false
# åœ¨/data/images/setuè·¯å¾„ä¸‹ç»´æŒçš„å›¾ç‰‡ç¼“å­˜æ•°é‡
cache_threshold: 6
# å…³æ³¨çš„ç”»å¸ˆåˆ—è¡¨(group_id:{user_id:user_name})
subscribe_puser_list:
  default:
    '446171': ãŠã¿ãªãˆã—
  '670404622':
    '12227191': AkiZero1510
    '26385162': ALå…‰
    '212801': Anmi@ç”»é›†ç™ºå£²ä¸­
    '5128504': Ao-å‡¹
    '87710606': Asaki
    '1980643': ASK
    '6662895': ATDAN-
    '333556': Bisonå€‰é¼ 
    '51198160': BODHI
    '267137': ddal
    '17178734': DDUCK KONG
    '32955491': far_side
    '4588267': Fukuroè¢‹å­
    '76749711': iasimo
    '8843541': JehyunğŸ¥°
    '21739409': Kaya
    '14046928': Kiriko
    '14538670': Lance
    '2811210': Mechari
    '2750098': mery
    '24234': mignon
    '4364687': NIAN
    '45249715': nike
    '2993192': Rosuuri
    '25760573': rurudo
    '16985944': Serika
    '13274275': SIKA
    '12505972': SyHan__
    '23098486': TOKKYU
    '1960050': torino
    '8983922': Totoria
    '28480895': Watersnake(æ°´è›‡)
    '20728711': WERI
    '346855': yamasan
    '8349252': Yolanda
    '2156906': åœåœ
    '926687': æ°·èœ&ç«ãƒ
    '888151': æ­¯ç£¨ãç²‰ã‚¢ã‚¤ã‚¹
    '18054080': ä¸œå±±
    '7618326': é¤¨ç”°ãƒ€ãƒ³
    '6049901': é¬¼é’ˆè‰
    '57681088': å¥ç
    '22334948': å¯ä¹ç±³mi
    '32221908': æ°¯é…¸é’¾çš„åˆ†è§£
    '50843589': æ˜æ—¥å¤œç©º
    '13829843': åƒåƒçµ
    '66371932': è©
    '67093476': æ—¥å®
    '86845153': å¦‚å¢¨
    '12539859': å„’å®…
    '465133': å¤©ä¸‰æœˆ
    '27517': è—¤ã¡ã‚‡ã“ï¼ˆè—¤åŸï¼‰
    '3297691': æ¡é‡
    '23291755': ä¸‡è€æ¿ - wboss
    '23338848': å’¸é±¼é­‰
    '22298878': é¸¦å±…
    '34054962': ä¸€akeng
    '2846708': æ­MIN
    '2642047': ã‚¢ã‚·ãƒ
    '10852879': ã‚‰ã£ã¡ã€‚
    '446171': ãŠã¿ãªãˆã—
    '19630602': ã‚¤ãƒ•æ˜Ÿé­”æ³•
    '77465110': ãƒ•ãƒˆã‚¹ãƒˆãƒ­1
    '2827964': ã¨ã´ã‚
    '70050825': ã»ã†ãæ˜Ÿ
    '24890072': ã‚ã†ãš / lows
    '3388329': ã›ã‚“ã¡ã‚ƒ
    '15558289': ã²ã’çŒ«@ã‚³ãƒŸã‚±101å§”è¨—ä¸­ã§ã™
    '24027989': ãŸã‘ã¡ãƒ¼
    '4816744': ã¿ã‚ã¹ã•ãã‚‰
    '9205975': ã¯ãªæ£®
